---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: git

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: gitea/gitea
    newTag: "1.22"

resources:
  - namespace.yaml
  - ingress.yaml
  - service.yaml
  - deployment.yaml
